# Generated by Django 2.2 on 2021-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=500, null=True)),
                ('date_time', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=500, null=True)),
                ('call_duration', models.CharField(blank=True, max_length=500, null=True)),
                ('call_language', models.CharField(blank=True, max_length=100, null=True)),
                ('call_status', models.CharField(blank=True, max_length=500, null=True)),
                ('transcription_start_date_time', models.DateTimeField(blank=True, null=True)),
                ('transcription_complete_date_time', models.DateTimeField(blank=True, null=True)),
                ('json_blob_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('mp3_blob_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('transcribed_file', models.CharField(blank=True, max_length=1000, null=True)),
                ('transcription_status', models.CharField(blank=True, default='Not Started', max_length=1000, null=True)),
            ],
        ),
    ]
