# Generated by Django 2.2 on 2021-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbcApp', '0002_currentprocesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='qa_color',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='qa_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='analytic',
            name='sentiment_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
