# Generated by Django 2.2 on 2021-06-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbcApp', '0003_auto_20210617_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytic',
        ),
        migrations.DeleteModel(
            name='CurrentProcessLog',
        ),
    ]
