# Generated by Django 2.2 on 2021-06-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbcApp', '0007_auto_20210624_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytic',
        ),
        migrations.DeleteModel(
            name='CurrentProcessLog',
        ),
    ]
