# Generated by Django 2.2 on 2021-06-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbcApp', '0009_analytic_currentprocesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytic',
        ),
        migrations.DeleteModel(
            name='CurrentProcessLog',
        ),
    ]
