# Generated by Django 2.2 on 2021-07-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AbcApp', '0011_analytic_currentprocesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytic',
        ),
        migrations.DeleteModel(
            name='CurrentProcessLog',
        ),
    ]
